FROM builder:latest

ARG GH_OWNER=gissehel
ARG GH_USER=gissehel
ARG GH_REGISTRY=ghcr.io
ARG IMAGE_NAME=project
ARG REPO_NAME=docker-project
ARG DESCRIPTION="Image description"

ARG BUILD_DATE=now
ARG VCS_REF=none
ARG VERSION=not-specified

LABEL \
      org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.authors="${GH_USER}" \
      org.opencontainers.image.url="https://github.com/${GH_OWNER}/${REPO_NAME}" \
      org.opencontainers.image.source="https://github.com/${GH_OWNER}/${REPO_NAME}" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.revision="${VCS_REF}" \
      org.opencontainers.image.vendor="${GH_OWNER}" \
      org.opencontainers.image.ref.name="${GH_REGISTRY}/${GH_USER}/${IMAGE_NAME}" \
      org.opencontainers.image.title="${IMAGE_NAME}" \
      org.opencontainers.image.description="${DESCRIPTION}" \
      org.label-schema.build-date="${BUILD_DATE}" \
      org.label-schema.vcs-ref="${VCS_REF}" \
      org.label-schema.name="${IMAGE_NAME}" \
      org.label-schema.version="${VERSION}" \
      org.label-schema.vendor="${GH_OWNER}" \
      org.label-schema.vcs-url="https://github.com/${GH_OWNER}/${REPO_NAME}" \
      org.label-schema.schema-version="1.0"